import type { PriorityConfig, Project, ProjectConfig, StatusConfig, Task } from '../types'
import { isTerminalStatus, sanitizeFileName } from '../utils'
import {
  appendYaml,
  FRONTMATTER_KEY,
  LINK_SENTINEL,
  stripAutoGeneratedContent,
  TASK_FRONTMATTER_KEY
} from './YamlParser'

// ─── Serialize ──────────────────────────────────────────────────────────────

/** Only the fields a project actually overrides are written; an empty override block is omitted. */
function serializeProjectConfig(config: ProjectConfig | undefined): Record<string, unknown> | null {
  if (!config) return null
  const out: Record<string, unknown> = {}
  if (config.statuses?.length) out.statuses = config.statuses
  if (config.priorities?.length) out.priorities = config.priorities
  writeNonPaletteConfig(out, config)
  return Object.keys(out).length ? out : null
}

/** The non-palette override fields shared by both the override and materialized shapes. */
function writeNonPaletteConfig(out: Record<string, unknown>, config: ProjectConfig): void {
  if (config.defaultView) out.defaultView = config.defaultView
  if (config.autoSchedule !== undefined) out.autoSchedule = config.autoSchedule
  if (config.kanbanShowSubtasks !== undefined) out.kanbanShowSubtasks = config.kanbanShowSubtasks
  if (config.kanbanShowDescriptionPreview !== undefined) {
    out.kanbanShowDescriptionPreview = config.kanbanShowDescriptionPreview
  }
}

/** The resolved palette effective for a project, threaded into the serializer for materialization. */
export interface EffectivePalette {
  statuses: StatusConfig[]
  priorities: PriorityConfig[]
}

/**
 * A genuine per-project palette override — an untagged `config` block that
 * declares its own statuses/priorities. Materialization must leave these
 * untouched (and untagged) so they keep winning through `configFor` (R25).
 */
function hasPaletteOverride(config: ProjectConfig | undefined): boolean {
  if (!config || config.materialized === true) return false
  return Boolean(config.statuses?.length) || Boolean(config.priorities?.length)
}

/**
 * Write-through materialization: snapshot the resolved palette into the `config`
 * block, tagged `materialized: true`, so the file self-describes its legal
 * vocabulary. Non-palette overrides (defaultView, …) are preserved.
 */
function materializeProjectConfig(
  config: ProjectConfig | undefined,
  palette: EffectivePalette
): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  if (palette.statuses.length) out.statuses = palette.statuses
  if (palette.priorities.length) out.priorities = palette.priorities
  out.materialized = true
  if (config) writeNonPaletteConfig(out, config)
  return out
}

/**
 * Build the `config` block for a project's frontmatter. A genuine override is
 * serialized as-is (untagged); otherwise the resolved palette is materialized
 * (tagged `materialized: true`) when one is supplied.
 */
function buildProjectConfig(
  config: ProjectConfig | undefined,
  palette: EffectivePalette
): Record<string, unknown> | null {
  if (hasPaletteOverride(config)) return serializeProjectConfig(config)
  if (palette.statuses.length || palette.priorities.length) return materializeProjectConfig(config, palette)
  return serializeProjectConfig(config)
}

export function serializeProject(
  project: Project,
  palette: EffectivePalette = { statuses: [], priorities: [] }
): string {
  const statuses = palette.statuses
  const seen = new Set<string>()
  const tasks: Task[] = []
  for (const t of project.tasks) {
    if (seen.has(t.id)) continue
    seen.add(t.id)
    tasks.push(t)
  }
  const taskIds = tasks.map((t) => t.id)

  const fm: Record<string, unknown> = {
    [FRONTMATTER_KEY]: true,
    id: project.id,
    title: project.title,
    description: project.description,
    color: project.color,
    icon: project.icon,
    taskIds,
    customFields: project.customFields,
    teamMembers: project.teamMembers,
    savedViews: project.savedViews.length ? project.savedViews : [],
    createdAt: project.createdAt,
    updatedAt: project.updatedAt
  }
  // Vault-relative directory this project lives in. Written only when declared,
  // so legacy projects don't gain a spurious key on rewrite; blank/absent falls
  // back to the file's parent folder on load (ProjectStore.projectDirectory).
  if (project.path) fm.path = project.path
  const config = buildProjectConfig(project.config, palette)
  if (config) fm.config = config

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  yamlLines.push(`# ${project.icon} ${project.title}`)
  yamlLines.push('')
  if (project.description) {
    yamlLines.push(project.description)
    yamlLines.push('')
  }
  if (tasks.length) {
    yamlLines.push('## Tasks')
    for (const t of tasks) {
      if (t.filePath) {
        const basename = t.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
        const check = isTerminalStatus(t.status, statuses) ? 'x' : ' '
        yamlLines.push(`- [${check}] [[${basename}|${t.title}]]`)
      }
    }
    yamlLines.push('')
  }

  return yamlLines.join('\n')
}

export function buildTaskFrontmatter(task: Task, project: Project, parentTask: Task | null): Record<string, unknown> {
  const fm: Record<string, unknown> = {
    [TASK_FRONTMATTER_KEY]: true,
    projectId: project.id,
    parentId: parentTask?.id ?? null,
    id: task.id,
    title: task.title,
    type: task.type,
    status: task.status,
    priority: task.priority,
    start: task.start,
    due: task.due,
    progress: task.progress,
    assignees: task.assignees,
    tags: task.tags,
    subtaskIds: task.subtasks.map((s) => s.id),
    dependencies: task.dependencies,
    createdAt: task.createdAt,
    updatedAt: task.updatedAt
  }
  if (task.completed) fm.completed = task.completed
  if (task.recurrence) fm.recurrence = task.recurrence
  if (task.timeEstimate !== undefined) fm.timeEstimate = task.timeEstimate
  if (task.timeLogs?.length) fm.timeLogs = task.timeLogs
  if (Object.keys(task.customFields).length) fm.customFields = task.customFields
  return fm
}

export function serializeTask(
  task: Task,
  project: Project,
  parentTask: Task | null,
  statuses: StatusConfig[] = []
): string {
  const fm = buildTaskFrontmatter(task, project, parentTask)

  const yamlLines: string[] = ['---']
  appendYaml(yamlLines, fm, 0)
  yamlLines.push('---')
  yamlLines.push('')
  const cleanDesc = stripAutoGeneratedContent(task.description)
  if (cleanDesc) {
    yamlLines.push(cleanDesc)
    yamlLines.push('')
  }

  // Managed immediate-parent backlink: a live [[wikilink]] to the item's IMMEDIATE
  // parent (parent task, else the project), additive to the frontmatter parentId.
  // The sentinel trails the [[link]] so the content detector can exclude the line
  // while Obsidian still graph-indexes the link.
  if (parentTask?.filePath) {
    const parentBasename = parentTask.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Parent: [[${parentBasename}|${parentTask.title}]] ${LINK_SENTINEL}`)
  } else {
    const projectBasename = project.filePath.replace(/^.*\//, '').replace(/\.md$/, '')
    yamlLines.push(`Project: [[${projectBasename}|${project.title}]] ${LINK_SENTINEL}`)
  }

  if (task.subtasks.length) {
    yamlLines.push('')
    yamlLines.push('## Subtasks')
    for (const sub of task.subtasks) {
      const subBasename = sub.filePath ? sub.filePath.replace(/^.*\//, '').replace(/\.md$/, '') : taskSlug(sub.title)
      const check = isTerminalStatus(sub.status, statuses) ? 'x' : ' '
      yamlLines.push(`- [${check}] [[${subBasename}|${sub.title}]]`)
    }
  }

  return yamlLines.join('\n')
}

/** Slug length cap, for path-length safety (Windows MAX_PATH, mobile, sync). */
export const TASK_SLUG_MAX_LENGTH = 60

function taskSlug(title: string): string {
  return sanitizeFileName(title).toLowerCase().replace(/\s+/g, '-').slice(0, TASK_SLUG_MAX_LENGTH)
}

/** Build the file path for a task .md file */
export function taskFilePath(taskTitle: string, folder: string): string {
  return `${folder}/${taskSlug(taskTitle)}.md`
}
