import { parseYaml } from 'obsidian'

export const FRONTMATTER_KEY = 'pm-project'
export const TASK_FRONTMATTER_KEY = 'pm-task'

// ─── Parse ──────────────────────────────────────────────────────────────────

export function parseFrontmatter(content: string): {
  frontmatter: Record<string, unknown> | null
  body: string
} {
  if (!content.startsWith('---')) return { frontmatter: null, body: content }
  const end = content.indexOf('\n---', 4)
  if (end === -1) return { frontmatter: null, body: content }
  const raw = content.slice(4, end)
  const body = content.slice(end + 4).trim()
  try {
    return { frontmatter: parseYaml(raw) as Record<string, unknown>, body }
  } catch {
    return { frontmatter: null, body: content }
  }
}

/**
 * Sentinel marking the store-managed immediate-parent backlink line in a note
 * body (e.g. `Part of [[Parent]] <!-- pm:link -->`). Write (YamlSerializer) and
 * detect (stripAutoGeneratedContent / ProjectStore content detector) share this
 * one constant so they never drift. The `[[link]]` stays before the sentinel so
 * Obsidian still graph-indexes it.
 */
export const LINK_SENTINEL = '<!-- pm:link -->'

/** True for a body line carrying the store-managed backlink sentinel. */
export function isManagedLinkLine(line: string): boolean {
  return line.includes(LINK_SENTINEL)
}

/** Strip auto-generated wiki-link lines from task body so they don't get duplicated on save */
export function stripAutoGeneratedContent(body: string): string {
  let result = body
  result = result
    .split('\n')
    .filter((line) => !isManagedLinkLine(line))
    .join('\n')
  result = result.replace(/^Project: \[\[.*\]\]$/gm, '')
  result = result.replace(/^Parent: \[\[.*\]\]$/gm, '')
  // Auto-generated child mirrors — `## Subtasks` on task notes, `## Tasks` on
  // project notes — are managed scaffolding, never human content.
  result = result.replace(/\n## Subtasks[\s\S]*$/, '')
  result = result.replace(/\n## Tasks[\s\S]*$/, '')
  return result.trim()
}

// ─── YAML Writer ────────────────────────────────────────────────────────────

/** Minimal YAML serializer (handles strings, numbers, booleans, arrays, objects) */
export function appendYaml(lines: string[], obj: Record<string, unknown>, indent: number): void {
  const pad = '  '.repeat(indent)
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) {
      lines.push(`${pad}${key}:`)
    } else if (typeof val === 'boolean') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'number') {
      lines.push(`${pad}${key}: ${val}`)
    } else if (typeof val === 'string') {
      const escaped = val.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
      lines.push(`${pad}${key}: "${escaped}"`)
    } else if (Array.isArray(val)) {
      if (val.length === 0) {
        lines.push(`${pad}${key}: []`)
      } else if (typeof val[0] === 'object') {
        lines.push(`${pad}${key}:`)
        for (const item of val) {
          const entries = Object.entries(item as Record<string, unknown>)
          if (entries.length === 0) continue
          const [firstKey, firstVal] = entries[0]
          lines.push(`${pad}  - ${firstKey}: ${JSON.stringify(firstVal)}`)
          for (const [k, v] of entries.slice(1)) {
            lines.push(`${pad}    ${k}: ${JSON.stringify(v)}`)
          }
        }
      } else {
        const items = val.map((v) => JSON.stringify(v)).join(', ')
        lines.push(`${pad}${key}: [${items}]`)
      }
    } else if (typeof val === 'object') {
      const keys = Object.keys(val)
      if (keys.length === 0) {
        lines.push(`${pad}${key}: {}`)
      } else {
        lines.push(`${pad}${key}:`)
        appendYaml(lines, val as Record<string, unknown>, indent + 1)
      }
    }
  }
}

/** Check if a project file uses the old embedded-tasks format */
export function isOldFormat(frontmatter: Record<string, unknown>): boolean {
  return Array.isArray(frontmatter.tasks) && frontmatter.tasks.length > 0 && !Array.isArray(frontmatter.taskIds)
}
